name: Update Star Citizen Data

on:
  schedule:
    # This runs the script every 12 hours (UTC)
    - cron: '0 */12 * * *'
  workflow_dispatch: # Allows you to run it manually with a button click

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Run UEX Builder
        env:
          UEX_API_KEY: ${{ secrets.UEX_API_KEY }}
        run: node uex-builder.js

      - name: Commit and Push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          
          if git diff --quiet game-data.js; then
            echo "No changes detected. Skipping update."
          else
            echo "Changes detected! Updating game-data.js..."
            git add game-data.js
            git commit -m "Auto-update: Fresh Market Prices"
            git push
          fi